apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: msa
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
