apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jenkins
  name: jenkins-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: msa
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jenkins
  name: jenkins-log-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: msa
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
