apiVersion: v1
entries:
  argo-cd:
  - annotations:
      artifacthub.io/changes: |
        - kind: changed
          description: Bump argo-cd to v2.10.3
      artifacthub.io/signKey: |
        fingerprint: 2B8F22F57260EFA67BE1C5824B11F800CD9D2252
        url: https://argoproj.github.io/argo-helm/pgp_keys.asc
    apiVersion: v2
    appVersion: v2.10.3
    created: "2024-07-10T04:57:20.659635737Z"
    dependencies:
    - condition: redis-ha.enabled
      name: redis-ha
      repository: https://dandydeveloper.github.io/charts/
      version: 4.26.1
    description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery
      tool for Kubernetes.
    digest: 3c0ee0f4addd6e932649c9b38207615de0f1fbca1794d89ae1105997d5ec11a1
    home: https://github.com/argoproj/argo-helm
    icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
    keywords:
    - argoproj
    - argocd
    - gitops
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - name: argoproj
      url: https://argoproj.github.io/
    name: argo-cd
    sources:
    - https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
    - https://github.com/argoproj/argo-cd
    urls:
    - argo-cd-6.7.2.tgz
    version: 6.7.2
generated: "2024-07-10T04:57:20.646068869Z"
