apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-config
  namespace: jenkins
data:
  daemon.json: |
    {
      "insecure-registries": ["${HARBOR_ADDR}"]
    }
